### ISSUE TITLE
질문 있어요 님께서 쓰신 쉽게따라만드는 파이썬 주식 자동매매 시스템에서 예제 실행시....

### ISSUE THREAD

**Issue by digerati73** [papadaks/SystemTrading#1]
질문 있어요 님께서 쓰신 쉽게따라만드는 파이썬 주식 자동매매 시스템에서 예제 실행시....

에러가 발생합니다.

물론 책에 쓰인 대로 따라 했고  마지막 페이지에 기술된것처럼 장 종료이후에 실행시 

물론, pycharm에서 main.py를 실행 하면

이상하게도

164페이지에 언급된 opstarter의
"버전처리를 받으시려면현재 실행중인.... 이란 팝업이 뜹니다. 그림 3-42  KOA업데이트란 그림처럼 되는데
처음엔 KOA studio 를 실행도 않했는데 pycharm만 실행해서 main.py만 실행시키는데 이게 왜 뜨지 
하여 어리석게도 pycharm을 끄라는 말인가도 생각해보기도 하였지만...

않되어 구글링 해보니

[해결법](https://cucumber.tistory.com/41?category=859988)

openapi ocx 문제로
C:\OpenAPI\opversionup.exe 를 실행해보면 된다 하니

말대로 위 팝업이 나타나지는 않는데...그뒤로 아무런 동작도 않하는듯 합니다. 
어떻게 된걸까요?

간혹 아래 출력창에 200개의 목록이 나오기도 하긴 하지만 그러더라도 시간이 상당시간 흐른후 나옵니다

참고로 어제 yes24 에 님의 책에 대한 서평을 올린 여행스케치 라고 합니다 ^^

빠르고 정확한 답변 기대할께요 ^^

이왕이면 저자가 추천이나 댓글을 서평에 달아주시면 무한한 영광이겠습니다. 댓글 달아주신다면 저자라고 말씀하시고 달아주시면 감사하겠습니다. ^^

**Comment by papadaks** [comment]
안녕하세요 선생님 
남겨주신 질문에는 두 가지 확인이 필요합니다.
1.main.py를 실행하시면 "버전처리를 받으시려면현재 실행중인.... 이란 팝업이 뜹니다. "라고 하셨는데
책에 기술된대로 KOA를 실행시켜 업데이트를 완료하셨다면 나오지 않았어야 할 부분입니다.
질문 내용만으로는 KOA 실행 및 업데이트까지 마치신 것인지 아니면 바로 main.py를 실행시킨 것인지 확인이 필요합니다.

만약 KOA를 통해 업데이트를 거치지 않으셨다 하더라도 main.py를 실행시 나오는 해당 팝업은 Pycharm을 끄는 것이 아닌
main.py의 실행을 중지한 뒤 확인 버튼을 누르시면 해결될 수 있습니다. (실행 중지는 파이참내 빨간색 버튼을 클릭하시면 됩니다.)

2.검색하신 해결책 적용 이후 동작을 안 하는 것 같다고 하셨는데, main.py 및 호출하시는 kiwoom.py 소스를 알려주시면 정확한 확인이 가능할 것 같습니다.

써주신 서평 잘 보았습니다. 
이렇게 자세하고 꼼꼼하게 남겨주신 분이 없었는데 감사합니다. 
저자 댓글을 어떻게 다는지 몰라서 일단 알게 되는대로 남기도록 하겠습니다^^

**Comment by digerati73** [comment]
안녕하세요 선생님
남겨주신 질문에는 두 가지 확인이 필요합니다.
1.main.py를 실행하시면 "버전처리를 받으시려면현재 실행중인.... 이란 팝업이 뜹니다. "라고 하셨는데
책에 기술된대로 KOA를 실행시켜 업데이트를 완료하셨다면 나오지 않았어야 할 부분입니다.
질문 내용만으로는 KOA 실행 및 업데이트까지 마치신 것인지 아니면 바로 main.py를 실행시킨 것인지 확인이 필요합니다.

 **=> 물론, KOA STUDIO 설치후 이상없이 실행됨을 확인하였습니다.  이때에는 위와 같은 팝업이 뜨질 않았습니다.
  그래서 더욱더 이상했습니다. KOA STUDIO 실행시에는 안뜨던게 왜 main.py를 실행하면 뜨는지 이상했지만
  구글링 결과대로 C:\OpenAPI\opversionup.exe 를 실행하여 일단 팝업은 뜨지 않게 되었습니다.**

만약 KOA를 통해 업데이트를 거치지 않으셨다 하더라도 main.py를 실행시 나오는 해당 팝업은 Pycharm을 끄는 것이 아닌
main.py의 실행을 중지한 뒤 확인 버튼을 누르시면 해결될 수 있습니다. (실행 중지는 파이참내 빨간색 버튼을 클릭하시면 됩니다.)

2.검색하신 해결책 적용 이후 동작을 안 하는 것 같다고 하셨는데, main.py 및 호출하시는 kiwoom.py 소스를 알려주시면 정확한 확인이 가능할 것 같습니다.

  **=> 코드는 github에서 내려 받은 그대로 실행하였습니다. 코드 수정은 별도로 하지 않았습니다.**

써주신 서평 잘 보았습니다.
이렇게 자세하고 꼼꼼하게 남겨주신 분이 없었는데 감사합니다.
저자 댓글을 어떻게 다는지 몰라서 일단 알게 되는대로 남기도록 하겠습니다^^

  **=> 기본적으로 서평의 댓글은 yes24  가입회원들만 가능합니다. 
  yes24 회원 가입하시면 댓글을 다실수 있습니다. ^^**

**Comment by papadaks** [comment]
안녕하세요.

간혹 아래 출력창에 200개의 목록이 나오기도 하긴 하지만 그러더라도 시간이 상당시간 흐른후 나옵니다
=> 업데이트 해야한다는 팝업이 나오지 않고 로그인창이 나온다면 우선적으로 정상동작하는 것이 맞습니다. 
이후 나온다는 200개의 목록은 프로그램 최초 실행시 유니버스 생성이 된 것으로 보입니다. 이후 콘솔창에서 확인하신 결과가 어떻게 될까요?

**Comment by digerati73** [comment]
아, 내 확인해보겠습니다.
