### ISSUE TITLE
RSIStrategy.py 파일의 222번 라인 오류

### ISSUE THREAD

**Issue by sigco3111** [papadaks/SystemTrading#10]
아래코드 호출시
df.loc[datetime.now().strftime('%Y%m%d')] = today_price_data

이런 오류발 발생합니다.
ValueError: cannot set a row with mismatched columns

오류코드 바로 위의 코드에서
df = universe_item['price_df'].copy()

universe_item 값은 아래와 같은데, pandas 데이터 형식이 아닌 듯 싶습니다.
{'code_name': '메리츠화재', 'price_df':          code code_name created_at
index                             
0      000060     메리츠화재   20220322}

어디를 고쳐야할까요?

**Comment by papadaks** [comment]
> today_price_data에 넣는 데이터가 어떻게 되나요?

뭔가 수정하신 것 같은데 
작성하신 코드를 깃허브에 올려주시면 봐드리겠습니다.

**Comment by sigco3111** [comment]
테스트 중 유니버스가 완전히 생성되기 전에 해당코드가 실행되어 발생된 문제임을 확인 했습니다.

바쁘실 텐데 질문 확인해주셔서 감사합니다.
