### ISSUE TITLE
main.py 실행 시 Process finished with exit code 오류

### ISSUE THREAD

**Issue by Parkjunghoons2** [papadaks/SystemTrading#11]
안녕하세요, 훌륭한 책 출판해 주셔서 감사합니다.

다름이 아니라 get_price_data 함수부터 main.py 실행시 
Process finished with exit code -1073740791 (0xC0000409) 에러가 뜹니다.

이럴 경우 어떻게 해결해야 할까요? 다른 구글링 문서에도 뚜렷한 해결책이 나오지 않아 이슈 올립니다.

감사합니다.

**Comment by Parkjunghoons2** [comment]
app = QApplication(sys.argv)
app.exec_() 
모두 처음과 마지막에 잘 입력했는데도 이런 에러가 뜨는 거면 버전 크래시가 있는 걸까요?

**Comment by papadaks** [comment]
> app = QApplication(sys.argv) app.exec_() 모두 처음과 마지막에 잘 입력했는데도 이런 에러가 뜨는 거면 버전 크래시가 있는 걸까요?

안녕하세요~ 제가 코로나에 걸렸어서 답이 많이 늦었습니다 ㅠㅜ
따라해주신 프로즉테 조금 잘못된 부분이 있지 않을까 싶습니다.
작성하신 소스 올려주시면 확인해드리겠습니다
