### ISSUE TITLE
안녕하세요. 큰맘먹고 시작했는데, 첫 실행에서 막혀서...

### ISSUE THREAD

**Issue by wondermt** [papadaks/SystemTrading#13]
온 인터넷을 검색하다 드디어 작가분을 만났네요. 완전초보구요.  30년전에 cobol로 뱅킹업무를 쫌 했던 경험이 있는데, 딴일 하다가 파이썬이 그나마 쉽다는 애기를 듣고 도전했는데...책 내용 그대로 코딩를 했는데...로그인 화면이 안 뜹니다. 모든 앞 과정도 책과 똑같이 했어요. 도와주세요. 

from PyQt5.QAxContainer import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *

class Kiwoom(QAxWidget):
    def __init__(self):
        super().__init__()

    def _make_kiwoom_instance(self):
        self.setControl("KHOPENAPI.KHOpenAPICtrl.1")

    def _set_signal_slots(self):
        self.connect(self._login_slot)

    def _login_slot(self, err_code):
        if err_code == 0:
            print("connected")
        else:
            print("not connected")

        self.login_event_loop.exit()

    def _comm_connect(self):
        self.dynamicCall("CommConnect()")

        self.login_event_loop = QEventLoop()

        self.login_event_loop.exec_()
---------------------------------------------------------------------------------
했는데 문제2개 뜨면서 실행하면 로그인 화면이 안뜨고 자체 루프를 도는 듯한 ...
그림은 못 올리나요?? 캡쳐해서 못 올리네요.
 하여간 다음과 같은 2개의 문제가 생겼습니다.

1. 사용되지 않는 import 문 'from PyQt5.QtWidgets import *'  :2번줄
2. 오타: 단어 'KHOPENAPI' 내 : 11번줄

**Comment by papadaks** [comment]
안녕하세요 선생님
우선 첨부해주신 소스에 아래 부분이 들여쓰기 되어 있는지 확인 부탁드립니다.
```
class Kiwoom(QAxWidget):
def init(self):
super().init()
```

이렇게 첨부해주셨는데
```
class Kiwoom(QAxWidget):
    def init(self):
        super().init()
```

처럼 들여쓰기가 되어 있어야 합니다
두번째는 kiwoom.py를 실행하신게 아닐까 싶습니다.

책에서 설명드린 것처럼 
main.py내에 Kiwoom클래스를 생성해 호출해보셨는지 확인 부탁 드립니다.

코볼 경험이 있으시면 파이썬도 잘 하실 것 같습니다. 
감사합니다.

**Comment by wondermt** [comment]
답변 감사합니다.
들여쓰기는 다 했고요. 복사/붙이기 과정에서 앞으로 나왔군요. 
그리고 main을 실행 시켰구요.
실행하면 아래창에 

C:\Users\UserK\anaconda3\envs\system_trading_py38_32\python.exe C:/Users/UserK/PycharmProjects/SystemTrading/main.py

이렇게 한줄이 나옵니다.
그 이후로 먹통이 되어서 작업관리자로 끝내고 나와야 해요. 

여기에는 사진은 못 올리나요??

**Comment by papadaks** [comment]
![Uploading Screenshot_20220713-134400_Chrome.jpg…]()

**Comment by papadaks** [comment]
![Uploading Screenshot_20220713-134400_Chrome.jpg…]()

**Comment by papadaks** [comment]
이미지 올리실 수 있습니다.
https://caileb.tistory.com/201
참고하셔서 올려주시면 보겠습니다.

추가로 main 함수 소스도 보여주시기 바랍니다.

**Comment by papadaks** [comment]
![image](https://user-images.githubusercontent.com/16892199/178652990-43f7baa7-fb42-4df5-b1de-bf062234c0b4.png)

**Comment by wondermt** [comment]
![화면 캡처 2022-07-13 140035](https://user-images.githubusercontent.com/109191753/178654317-03da9e18-a157-4a80-bca6-d8a52f00762b.png)

미치갔네...
난 왜 안되죠?? 복사&붙이기
했는데...

아. 업로드를 해야 하는구나...ㅋ

**Comment by wondermt** [comment]
![image](https://user-images.githubusercontent.com/109191753/178654777-20b7031f-f96b-4f81-96cb-71c97c1e5271.png)

**Comment by wondermt** [comment]
![image](https://user-images.githubusercontent.com/109191753/178654991-d242d0a8-0bdf-442e-a801-471fac6dd429.png)

**Comment by papadaks** [comment]
책에 적혀있는 소스와 다른 것 같습니다.
이렇게 해보실래요 
```
    def __init__(self):
        super().__init__()
        self._make_kiwoom_instance()
```

**Comment by papadaks** [comment]
self._make_kiwoom_instance() 를 호출 안하시는 것 같습니다.

**Comment by papadaks** [comment]
전체 소스를 참고해주세요
https://github.com/papadaks/SystemTrading/blob/master/api/Kiwoom.py

**Comment by wondermt** [comment]
아. 자료실에 있는 것  저도 다운 받긴 했어요.
저렇게 고치고 main을 실행하면 로그인 위젯이 뜨는거 아닌가요??
이렇게 나오는데...
![image](https://user-images.githubusercontent.com/109191753/178657876-f9e0c9a1-029c-4ff3-b14c-3c4e5bee11ba.png)

**Comment by papadaks** [comment]
함수명에 오타가 있으십니다.
_make_kiwoon > 이게 아니라
_make_kiwoom 입니다~

**Comment by wondermt** [comment]
아. 예
지금 보고 고치고 다시 돌렸어요.
![image](https://user-images.githubusercontent.com/109191753/178658646-b015768a-3286-4d9a-a1a9-28f846784e7b.png)

**Comment by papadaks** [comment]
def _set_signal_slots(self): 도 잘못되어있습니다.
 self.OnEventConnect.connect(self._login_slot)로 수정 바랍니다.

**Comment by wondermt** [comment]
아. 제가 key_in은 자신 있었는데...ㅋ
죄송함다.
![image](https://user-images.githubusercontent.com/109191753/178659450-c97f8275-b221-442b-b531-75ca472932aa.png)

**Comment by wondermt** [comment]
떴어요!!!!!~~~~~~
![image](https://user-images.githubusercontent.com/109191753/178659949-f174c479-5f71-4ff2-b2c1-a18ec92f00b3.png)

**Comment by wondermt** [comment]
와~~
너무 감사요 ^^

**Comment by papadaks** [comment]
다행입니다 ^^
괜찮으시면 작성해주신 리뷰 수정 부탁 드립니다 선생님
http://www.yes24.com/Product/goods/104688270

**Comment by wondermt** [comment]
앞으로 더욱 더 키인할 때 조심하면서 공부 할께요.
전체 소스를 카피해서 그냥 돌리는 것은 공부하는데 의미가 없을 것 같아서 천천히 읽어 가면서 할께요.
다시 한 번 감사합니다.

**Comment by papadaks** [comment]
넵 ^^

**Comment by wondermt** [comment]
아. 
알겠습니다.^^

**Comment by papadaks** [comment]
감사합니다.
어려운 부분 있으시면 이슈 열어주세요~
