### ISSUE TITLE
도움 요청드려요.

### ISSUE THREAD

**Issue by wondermt** [papadaks/SystemTrading#14]
예제 다운받아서 대체하다가 엉망이 됐어요.
다 밀어버리고 예제만 깔끔하게 다운받아 설치하는 법은 없나요??

파이참에는 프로젝트삭제 메뉴가 없던데...

![image](https://user-images.githubusercontent.com/109191753/178771957-ddaaf6ce-fdac-42c3-b9ad-1c47bbff216d.png)

**Comment by papadaks** [comment]
다운 받아서 압축해제 하고 파이참을 동작시키신게 아닐까 싶습니다.
예제 파일을 zip으로 다운 받지 마시고 다음 참조해서 연동 시켜보시겠어요
https://velog.io/@dayhun/PyCharm-GitHub-%EC%97%B0%EB%8F%99

https://nightime-mech.tistory.com/39

**Comment by wondermt** [comment]
감사합니다.
다운은 잘 된 것 같은데...
main을 돌려보면 다음과 같은 에러가 뜨고 안 돌아 가요. 다른 모듈프로그램들도 비슷하고...
일단 돌아가야 뭐도 할 텐데... ㅜ

![image](https://user-images.githubusercontent.com/109191753/179239496-2d2c28a0-fe55-43a8-ae3f-4ad3da57c9f4.png)

**Comment by papadaks** [comment]
안녕하세요 
혹시 지금 캡쳐하신 화면의 프로젝트 anaconda 가상환경 연결이 잘 되었을까요?

**Comment by wondermt** [comment]
감사합니다.

![image](https://user-images.githubusercontent.com/109191753/180629794-e1002ef0-7cad-4c9b-977f-bce3e62c7423.png)

conda env list  를 입력하면 위와 같이 뜨는데...

책에서 보면 가상환경이 하나일때는 파이참을 실행하면 저절로 그 하나의 가상환경으로 연결된다고 해서요. 저는 아나콘다로 책에서 지정한 가상환경이 하나밖에 없어요. 다른 설정을 해야 하나요??

------------------------------------------------------------------------------------------
데이타 베이스 연결하려고 돌렸더니 아래처럼 또 ...ㅜ
![image](https://user-images.githubusercontent.com/109191753/180630530-3861e150-a4f7-42e6-8c8a-37bdc83fdc03.png)

------------------------------------------------------------------------------------------------
질문하나 드려요. 예제 다운받을 때 바탕화면에 예제화일들을 담은 systemTrading이라는 폴더가 생겼잔아요. 그폴더는 계속 그자리에 있어야 하나요?? 삭제하거나 다른 폴더로 이동하면 안 되나요??

가상환경과 여러 패키지와 연결하여 개발하는 것이 저한테는 약간 낮설군요. 옛날에는 메인 프레임하나에서만 돌리니까 그런것이 없었는데 여러 시스템과 연결하니 기본 환경설정 자체가 어려워요. 개념도 잘 안 서고...



감사합니다.^^

**Comment by papadaks** [comment]
conda env list 를 입력하면 위와 같이 뜨는데...

책에서 보면 가상환경이 하나일때는 파이참을 실행하면 저절로 그 하나의 가상환경으로 연결된다고 해서요. 저는 아나콘다로 책에서 지정한 가상환경이 하나밖에 없어요. 다른 설정을 해야 하나요??
=> 네 파이참에서 꼭꼭곡 설정하셔 야 합니다~~
책에서 설명드린 바는 가상환경이 하나일 때 선택할 게 하나라는 의미이지 자동 선택된다는 말이 아닙니다!!

**Comment by papadaks** [comment]
import requests from bs4 이부분은 잘못된 문법입니다
또 requests와 bs4는 서로 다른 모듈이라 에러가 납니다
from beautifulsoup4 import bs4 혹은 다음처럼 2줄로 구성하시는게 옳습니다. 

import requests
import beautifulsoup4

**Comment by papadaks** [comment]
질문하나 드려요. 예제 다운받을 때 바탕화면에 예제화일들을 담은 systemTrading이라는 폴더가 생겼잔아요. 그폴더는 계속 그자리에 있어야 하나요?? 삭제하거나 다른 폴더로 이동하면 안 되나요??

-> 이동하셔도 됩니다. 다만 그럴 경우 파이참에서 이미 열어놓은 해당 프로젝트가 못찾을 수도 있어서 project > open을 다시 하셔야하실 수도 있습니다.

가상환경과 여러 패키지와 연결하여 개발하는 것이 저한테는 약간 낮설군요. 옛날에는 메인 프레임하나에서만 돌리니까 그런것이 없었는데 여러 시스템과 연결하니 기본 환경설정 자체가 어려워요. 개념도 잘 안 서고...
-> 네 가상환경을 처음 사용하시면 충분히 그러실 수 있습니다. 책에서 설명드린 것처럼 tool kit정도로 생각해주시면 좋겠습니다.
