### ISSUE TITLE
SQlite 모듈이 작동이 안됩니다...도와주세요ㅠ

### ISSUE THREAD

**Issue by Be-Smile-ing** [papadaks/SystemTrading#15]
SQlite 모듈이 작동이 안됩니다....
구글링해보니 SQlite 사이트에서 DLL 파일을 새로 다운로드 받은 후 Anaconda 폴더에 넣으면 해결된다는 글이 많던데...
해당 방법으로 해도 하기와 같이 Import Error가 발생합니다.
도와주세요....

> **C:\Users\User\anaconda3\envs\auto_py38_32\python.exe C:/Users/User/PycharmProjects/AutoTrading/util/db_helper.py
> Traceback (most recnt call last):
> File "C:/Users/User/PycharmProjects/AutoTrading/util/db_helper.py", line 1, in <module>
> import sqlite3
> File "C:\Users\User\anaconda3\envs\auto_py38_32\lib\sqlite3\__init__.py", line 23, in <module>
> from sqlite3.dbapi2 import *
> File "C:\Users\User\anaconda3\envs\auto_py38_32\lib\sqlite3\dbapi2.py", line 27, in <module>
> from _sqlite3 import *
> ImportError: DLL load failed while importing _sqlite3: 지정된 모듈을 찾을 수 없습니다.**

**Comment by papadaks** [comment]
네 안녕하세요
저도 처음 보는 에러인데요

저도 찾아본 방법대로 확인을 부탁드립니다.
[방법1](https://www.inflearn.com/questions/37360/%ED%95%B4%EA%B2%B0%EB%B2%95%EA%B3%B5%EC%9C%A0-importerror-dll-load-failed-%EC%A7%80%EC%A0%95%EB%90%9C-%EB%AA%A8%EB%93%88%EC%9D%84-%EC%B0%BE%EC%9D%84-%EC%88%98-%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4)

**Comment by Be-Smile-ing** [comment]
> 

해당방법은 이미 다 해본건데 안되서 문의드렸습니다.

Project 새로 생성해서 기존 python 파일 복붙하니 되네요...
어떤게 문제였는지 이유는 모르겠습니다...(해결된 이유도 모르겠고요...)

이 이슈는 클로징 해주세요:)
