### ISSUE TITLE
가상환경과 프로젝트 연결작업

### ISSUE THREAD

**Issue by Ben6306** [papadaks/SystemTrading#17]
32페이지에서 가상환경 path 를 선택했지만 python.exe파일을 못 찾는 것 같습니다. 선택할 수가 없는데 어떻게 해야 할까요?
교재와 차이점은 Anaconda 설치시 현재 사이트에서는  32bit 가 없어서 어쩔수 없이  64bit로 설치를 했습니다. 방법이 있을까요??

**Comment by Ben6306** [comment]
"System Interpreter" 옵션을 선택하고 "..." 버튼을 클릭하여 파일 시스템을 탐색합니다.
C:\Users\<사용자 이름>\Anaconda3\envs\myenv\ 디렉토리로 이동하여 python.exe 파일을 수동으로 선택합니다.
위와 같이 했더니 연동이 된 듯 합니다. conda 환경 대신  system interpreter로 해도 되나요??

**Comment by dustin-forest** [comment]
안녕하세요. 저술해주신 책[파이썬 주식 자동매매시스템]을 바탕으로 큰 도움을 얻어 공부하고 있습니다.
우선 너무 감사합니다.

궁금한 점이 있어 코멘트 남깁니다.
책의 코드에서, 실제 동작시 RSIStrategy.py 안에 run 함수에서 대부분의 기능이 구현되는데요... run함수 내부에서 kiwoom.get_balance 함수를 호출하면 프로그램이 정지하는 거 같습니다.
run함수 내부에서 balance를 업데이트해야 할 때가 필요할 수 있을거 같아서요...
run 함수 내부에서 get_balance함수를 사용할 수 있게 하려면 어떻게 해야 할까요?
며칠 고민하다 잘 안되어서 문의 드립니다.
만약 시간이 되신다면 답변 부탁드립니다.

좋은 책, 쉬운 설명 감사드립니다.

**Comment by papadaks** [comment]
안녕하세요.
답이 너무 늦었네요.
그렇게 하셔도 무방합니다.
이 이슈는 종료하겠습니다
