### ISSUE TITLE
run함수 내부에서 kiwoom.get_balance 함수를 호출시 프로그램 정지

### ISSUE THREAD

**Issue by dustin-forest** [papadaks/SystemTrading#18]
안녕하세요. 저술해주신 책[파이썬 주식 자동매매시스템]을 바탕으로 큰 도움을 얻어 공부하고 있습니다.
우선 너무 감사합니다.

궁금한 점이 있어 코멘트 남깁니다.
책의 코드에서, 실제 동작시 RSIStrategy.py 안에 run 함수에서 대부분의 기능이 구현되는데요... 
책 코드 그대로 사용하여 run함수 내부에서 kiwoom.get_balance 함수를 호출하면 프로그램이 정지하는 거 같습니다.
(참고로 get_order, gert_deposit 모두 동일한 현상이 일어납니다.)

run함수 내부에서 balance를 업데이트해야 할 때가 필요할 수 있을거 같아서요...
run 함수 내부에서 get_balance함수를 사용할 수 있게 하려면 어떻게 해야 할까요?

며칠 고민하다 잘 안되어서 문의 드립니다.
만약 시간이 되신다면 답변 부탁드립니다.

좋은 책, 쉬운 설명 감사드립니다.

**Comment by dustin-forest** [comment]
def run(self):
        """실질적 수행 역할을 하는 함수"""
        while self.is_init_success:
            try:
                # (0)장중인지 확인
                if not check_transaction_open():
                    print("장시간이 아니므로 5분간 대기합니다.")
                    time.sleep(5 * 60)
                    continue

                self.kiwoom.get_balance()             <------------  이렇게 함수를 추가하면 프로그램이 정지합니다.

                for idx, code in enumerate(self.universe.keys()):
                    print('[{}/{}_{}]'.format(idx + 1, len(self.universe), self.universe[code]['code_name']))
                    time.sleep(0.5)

**Comment by papadaks** [comment]
맞습니다. run 함수 안에서 tr 호출시 응답을 기다리면서 그런 현상이 발생합니다.
책의 원래 의도는 여러전략을 사용하실 수 있게  rsistrategy.py 같이 전략명을 기준으로 모듈을 구분했었습니다.

하나의 파일로 합쳐서 사용하시려면 이분의 코드를 참고하시면 좋겠습니다.
https://github.com/programgarden/book/blob/master/%EA%B5%90%EC%9E%AC%ED%95%99%EC%8A%B5%EC%BD%94%EB%93%9C_4%EC%87%84/example/kiwoom/kiwoom.py
