### ISSUE TITLE
본 교재(파이썬 주식 자동매매 시스템)에서는 파이참과 아나콘다를 반드시 써야 하나요?

### ISSUE THREAD

**Issue by naver0103** [papadaks/SystemTrading#19]
안녕하세요. 파이썬 비기너이면서 본 교재 잘 보고 있습니다.
언급 드린대로 파이참이라는 에디터와 아나콘다라는 가상환경으로 반드시 해야 하는지 궁금합니다.
현재 트렌드라면 vscode를 에디터로 많이 사용하고 있으며, 아나콘다가 용량이나 영역문제로 pc가 버벅거리는 문제때문에 가상환경(?)이라는 공간에서 작업을 해야 하는지 궁금합니다. PC용량과 속도는 많이 빨라진게 사실이거든요.

또한 본 교재에서는 선택의 여지가 없이 키움증권 특성상 32bit(OCX)로 파이썬을 맞춰서 진행하겠지만, 많은 분석 및 추세프로그램들은 64bit로 나온 교재들이 있어서 오히려 64bit를 사용하는 증권회사를 선택해야 하나 기로에 있습니다.
64bit로 바꾸는 작업이 증권회사 담당자는 아니시겠지만, 저자님이 보시기에는 그렇게 어려울까요?

**Comment by papadaks** [comment]
1.pc가 버벅거리는 문제 때문에 가상환경을 쓰는게 아닙니다^^
2.이미 사용하는 에디터가 있다면 파이참, 아나콘다를 반드시 쓰실 필요 없습니다. 아무것도 사용해본 적 없는 분들을 위해 가이드를 드린 것입니다.
3.다른 증권회사를 사용하시면 본 책을 보시는게 의미가 없습니다.
32비트를 제공하는 키움 api를 사용하기 위해서는 준수해주시면 좋겠습니다.
감사합니다.
