### ISSUE TITLE
5.7 절에서 예제대로 따라했는데 오류가 납니다

### ISSUE THREAD

**Issue by MBall3000** [papadaks/SystemTrading#3]
안녕하세요 작가님 책 보며 공부하는 중인데 5.7 절에서 오류가 나서 문의  드립니다

![error](https://user-images.githubusercontent.com/95897567/145515240-7bb64182-9379-4d5a-b1ef-7c5216954b57.jpg)

main.py 파일을 실행하면 장중이고 universe 라는 DB도 구성 완료되어 있는데 실행 도중 sqlite 관련 오류가 나며 제대로 실행되지 않습니다

작가님이 올려주신 소스 코드와 비교 해보아도 제가 진행한 부분까지는 완전히 동일한 걸 확인했습니다

모쪼록 바른 해결책을 알려주시면 고맙겠습니다

**Comment by papadaks** [comment]
안녕하세요 선생님 구매해주셔서 감사합니다.
해당 에러는 000060(메리츠화재)가 유니버스에 존재하는데 해당 테이블이 존재하지 않아서 발생하는 에러입니다.
.db 파일을 지운 후 프로그램을 다시 실행해보시기 바랍니다

**Comment by MBall3000** [comment]
> 안녕하세요 선생님 구매해주셔서 감사합니다. 해당 에러는 000060(메리츠화재)가 유니버스에 존재하는데 해당 테이블이 존재하지 않아서 발생하는 에러입니다. .db 파일을 지운 후 프로그램을 다시 실행해보시기 바랍니다

유니버스에 000060(메리츠화재)가 존재하고 DB에도 있습니다
혹시나 해서 .db파일을 지우고 새로 생성하여 실행해봤으나 여전히 같은 부분에서 에러가 나며 진행되지 않네요

**Comment by papadaks** [comment]
안녕하세요. 유니버스에 있는 00060말고
000060 이름의 테이블이 없으신 것 같습니다.
책에도 기재했듯이 유니버스에 들어있는 종목들은 종목코드 이름의 테이블이 생성되어야 합니다.
테이블 생성은 장이 끝난 오후 3시반 이후에 프로그램을 동작시켜주시면 됩니다.
감사합니다.

**Comment by MBall3000** [comment]
> 

장 마감 후에 동작해보니 63번째에서 이런 오류가 나오면서 진행되지 않네요
에러 구문을 구글링 해보니 값을 찾지 못해서 이런 오류가 나오는 거 같습니다
그래서 DB를 확인해보니 63번째 테이블과 인덱스에서 잘못된 값이 들어가 있는거 같습니다
![error2](https://user-images.githubusercontent.com/95897567/145777616-dc12ad33-a911-4584-b728-882f105dad00.jpg)
![error2-1](https://user-images.githubusercontent.com/95897567/145777625-ce6dd1cd-ac7c-41d6-8dd1-f6b3c9bf105f.jpg)
![error2-2](https://user-images.githubusercontent.com/95897567/145777628-07202bf4-4885-453e-a26f-a83191fe88d0.jpg)

테이블을 확인해보니 62번째 136490 이후로는 생성되어 있지 않네요

**Comment by papadaks** [comment]
안녕하세요 137310 종목의 가격 데이터 크롤링시 키움증권으로 noneType을 전달 받아서 발생한 에러입니다.
인덱스가 잘못 생성된게 아니라 137310의 인덱스 및 테이블이 생성되지 않은 것입니다. 표시하신 universe 테이블 및 인덱스는 정상입니다. 23:59분 전에 프로그램을 재실행해 아래와 같이 137310 가격 데이터를 얻어오면 됩니다. 재실행 부탁 드립니다. 
![image](https://user-images.githubusercontent.com/16892199/145817665-13c48990-0778-49df-9fee-0b37628ab43f.png)

**Comment by MBall3000** [comment]
> 안녕하세요 137310 종목의 가격 데이터 크롤링시 키움증권으로 noneType을 전달 받아서 발생한 에러입니다. 인덱스가 잘못 생성된게 아니라 137310의 인덱스 및 테이블이 생성되지 않은 것입니다. 표시하신 universe 테이블 및 인덱스는 정상입니다. 23:59분 전에 프로그램을 재실행해 아래와 같이 137310 가격 데이터를 얻어오면 됩니다. 재실행 부탁 드립니다. ![image](https://user-images.githubusercontent.com/16892199/145817665-13c48990-0778-49df-9fee-0b37628ab43f.png)

장종료후 재실행을 해도 제대로 된 값을 받아오질 못하네요
키움 API에 들어가서 확인 해보면 137310의 일봉데이터가 존재하기는 합니다
이건 키움API에 문제가 있는건가요?
![error2-3](https://user-images.githubusercontent.com/95897567/146022705-d25a3842-65ae-4828-98ac-19bccb96ab87.jpg)

**Comment by papadaks** [comment]
키움api의 문제일 확률도 있기는 하지만 koa에서 얻어오는 걸로 봐서 그럴 가능성이 낮을 것 같습니다.

main.py에서 실행시 여전히 137310 종목 10081호출 과정에서 to_sql 함수 에러가 난다는 말씀이신가요?

**Comment by MBall3000** [comment]
> 키움api의 문제일 확률도 있기는 하지만 koa에서 얻어오는 걸로 봐서 그럴 가능성이 낮을 것 같습니다.
> 
> main.py에서 실행시 여전히 137310 종목 10081호출 과정에서 to_sql 함수 에러가 난다는 말씀이신가요?

네 어제 밤 11시 넘어 실행했는데도 저부분에서 호출해오지 못하네요
이따 오후 4시 넘어 다시 실행해 보겠습니다

**Comment by papadaks** [comment]
네 알겠습니다. 다시 해보셔도 안되시면 137310 해당종목을 universe 테이블에서 제거하는 방법을 사용하셔도 좋을 것 같습니다~

**Comment by MBall3000** [comment]
>

**Comment by MBall3000** [comment]
> 네 알겠습니다. 다시 해보셔도 안되시면 137310 해당종목을 universe 테이블에서 제거하는 방법을 사용하셔도 좋을 것 같습니다~

오후 5시 30분 쯤 실행해 봤는데 여전히 같은 부분에서 오류가 납니다
universe 테이블에서 137310을 지우거나 건너뛰어서 진행하고 싶은데 방법을 모르겠네요
혹시 저자님 메일 있으시면 제가 지금까지 작성한 코드들을 보내드리고 싶습니다

**Comment by papadaks** [comment]
> > 네 알겠습니다. 다시 해보셔도 안되시면 137310 해당종목을 universe 테이블에서 제거하는 방법을 사용하셔도 좋을 것 같습니다~
> 
> 오후 5시 30분 쯤 실행해 봤는데 여전히 같은 부분에서 오류가 납니다 universe 테이블에서 137310을 지우거나 건너뛰어서 진행하고 싶은데 방법을 모르겠네요 혹시 저자님 메일 있으시면 제가 지금까지 작성한 코드들을 보내드리고 싶습니다

안녕하세요. 137310 삭제는 아래처럼 universe 테이블에서 137310 선택하신 후 마우스 우클릭 > 레코드 삭제를 하면 됩니다. 
![image](https://user-images.githubusercontent.com/16892199/146205406-1361dfb2-5bf3-4c8e-9bdf-a61681016450.png)

소스는 독자님 깃허브에 올려주시면 가서 보도록 하겠습니다~

**Comment by MBall3000** [comment]
> > > 네 알겠습니다. 다시 해보셔도 안되시면 137310 해당종목을 universe 테이블에서 제거하는 방법을 사용하셔도 좋을 것 같습니다~
> > 
> > 
> > 오후 5시 30분 쯤 실행해 봤는데 여전히 같은 부분에서 오류가 납니다 universe 테이블에서 137310을 지우거나 건너뛰어서 진행하고 싶은데 방법을 모르겠네요 혹시 저자님 메일 있으시면 제가 지금까지 작성한 코드들을 보내드리고 싶습니다
> 
> 안녕하세요. 137310 삭제는 아래처럼 universe 테이블에서 137310 선택하신 후 마우스 우클릭 > 레코드 삭제를 하면 됩니다. ![image](https://user-images.githubusercontent.com/16892199/146205406-1361dfb2-5bf3-4c8e-9bdf-a61681016450.png)
> 
> 소스는 독자님 깃허브에 올려주시면 가서 보도록 하겠습니다~

제 깃허브에 소스 올려놨습니다
귀찮으시겠지만 모쪼록 체크 부탁 드립니다

**Comment by MBall3000** [comment]
63번 지우고 진행해보니 이젠 74번에 막히네요
똑같이 'Non Type'오류 입니다
데이터의 문제가 아니라 소스상의 문제일 듯 한데 다시 살펴보겠습니다

**Comment by papadaks** [comment]
> 63번 지우고 진행해보니 이젠 74번에 막히네요 똑같이 'Non Type'오류 입니다 데이터의 문제가 아니라 소스상의 문제일 듯 한데 다시 살펴보겠습니다

독자님 깃허브에 들어가서 확인해보았습니다.
좌측이 독자님이 올린 소스인데 들여쓰기 해제해주시기 바랍니다. 
![image](https://user-images.githubusercontent.com/16892199/146647094-7ddb8fa0-f4fa-4ba3-9dbd-4e64a80441d8.png)

**Comment by MBall3000** [comment]
> > 63번 지우고 진행해보니 이젠 74번에 막히네요 똑같이 'Non Type'오류 입니다 데이터의 문제가 아니라 소스상의 문제일 듯 한데 다시 살펴보겠습니다
> 
> 독자님 깃허브에 들어가서 확인해보았습니다. 좌측이 독자님이 올린 소스인데 들여쓰기 해제해주시기 바랍니다. ![image](https://user-images.githubusercontent.com/16892199/146647094-7ddb8fa0-f4fa-4ba3-9dbd-4e64a80441d8.png)

오 그 부분 들여쓰기 수정하니 정상 작동 하네요!
드디어 다음 단계로 넘어갈 수 있게 되었습니다
감사합니다 ㅜㅜ

**Comment by papadaks** [comment]
> > > 63번 지우고 진행해보니 이젠 74번에 막히네요 똑같이 'Non Type'오류 입니다 데이터의 문제가 아니라 소스상의 문제일 듯 한데 다시 살펴보겠습니다
> > 
> > 
> > 독자님 깃허브에 들어가서 확인해보았습니다. 좌측이 독자님이 올린 소스인데 들여쓰기 해제해주시기 바랍니다. ![image](https://user-images.githubusercontent.com/16892199/146647094-7ddb8fa0-f4fa-4ba3-9dbd-4e64a80441d8.png)
> 
> 오 그 부분 들여쓰기 수정하니 정상 작동 하네요! 드디어 다음 단계로 넘어갈 수 있게 되었습니다 감사합니다 ㅜㅜ

다행입니다^^ 이슈 종료하겠습니다~
