### ISSUE TITLE
main.py 실행시키고 data 불러올때 갯수 문의

### ISSUE THREAD

**Issue by babihong** [papadaks/SystemTrading#4]
안녕하세요? 
작가님 책 재밌게 잘 보고 있구요~좋은 내용 잘 배우고 있습니다. 제가 현재 겪고 있는 문제 아래와 같이 정리 해봤는데 도움 주실 수 있으실까요? 
 
제가 main.py 을 실행시키면 아래와 같이  data가 받아왔었습니다. 
1.초기에는 키움에서 계속 데이터를 요청해서 그런지 어느 시점 후엔 연결이 몇 번 끊기고 해서 몇 번 계속 진행 했었고,
2.몇일 후  다음 날 다시 실행 시켰을 때는 일부 종목 코드가 없다고 하면서 sql error가 났었는데 여기 계시판에 다른분도 같은 에러나서  해당 종목을 db에서 list 삭제 하는 답변이 있어서 에러나는 모든 리스트 삭제 했더니 더 이상 에러는 안났습니다. 
3.그 다음으로 실행하니 아래와 같이 데이터가 잘 받아와 지는데 db 갯수가 200개가 아닌 저는 91개밖에 안되는 것 같은데 왜 그런지 이유를 모르겠습니다. 그리고 2일 정도 모의서버에서 실행 시켜보니 주식종목 1-91개까지만 반복적으로 카운팅만 하고 매매는 조건이 안맞아서 진행이 안되는 것 같습니다. 코디는 현재 배우는 중이라서 책에서 제공하는 소스 그대로 사용했습니다. 
혹시 이 내용 보시고 개선 방향 도움 주시면 감사하겠습니다.

---------------------------- 
[Kiwoom] _on_receive_tr_data is called 0001 / opt10081_req / opt10081
[Kiwoom] _on_receive_tr_data is called 0001 / opt10081_req / opt10081
[Kiwoom] _on_receive_tr_data is called 0001 / opt10081_req / opt10081
(91/91) 031310
[Kiwoom] _on_receive_tr_data is called 0001 / opt10081_req / opt10081
[Kiwoom] _on_receive_tr_data is called 0001 / opt10081_req / opt10081
[Kiwoom] _on_receive_tr_data is called 0001 / opt10081_req / opt10081
[Kiwoom] _on_receive_tr_data is called 0001 / opt10081_req / opt10081
[Kiwoom] _on_receive_tr_data is called 0001 / opt10081_req / opt10081
[Kiwoom] _on_receive_tr_data is called 0001 / opt10081_req / opt10081

**Comment by babihong** [comment]
위에 것 해결 되었습니다. ^^
RSIStrategy.db file삭제하고 다시 main.py 실행하니까 db file생성되고 list도 200개로 다시 나오네요~
근데 이전에는 어떻게 91개만 나왔었고 그 이후로 list가 200개로 채워지지 않는지는 아직 잘 이해가 안가네요..

**Comment by papadaks** [comment]
> 위에 것 해결 되었습니다. ^^ RSIStrategy.db file삭제하고 다시 main.py 실행하니까 db file생성되고 list도 200개로 다시 나오네요~ 근데 이전에는 어떻게 91개만 나왔었고 그 이후로 list가 200개로 채워지지 않는지는 아직 잘 이해가 안가네요..

안녕하세요. 
첨부해주신 출력결과를 보니 유니버스가 91개만 생성되어서 그랬던 것 같습니다.
최초 유니버스 종목은 200개가 생성되어야 하는데 처음 RSIStrategy.db를 생성하실 때 에러가 발생해서 그런게 아닐까 싶습니다.
저는 최초 설정한 200개에 못 미치게 유니버스가 생성되는 것을 본적은 없는데 아마 일시적인 에러가 아닐까 생각됩니다.
