### ISSUE TITLE
모든 코드 작성 후 실행하는데 오류가 발생합니다.

### ISSUE THREAD

**Issue by adfhief** [papadaks/SystemTrading#5]
line 메세지 관련 코드를 제외한 모든 코드를 작성 후 main.py를 실행했는데 사진의 오류가 발생하였습니다. 
![image](https://user-images.githubusercontent.com/95861458/150713658-296bfbd7-5530-476f-a710-04964e8abe8c.png)
어떻게 해결해야 하나요?

**Comment by papadaks** [comment]
> line 메세지 관련 코드를 제외한 모든 코드를 작성 후 main.py를 실행했는데 사진의 오류가 발생하였습니다. ![image](https://user-images.githubusercontent.com/95861458/150713658-296bfbd7-5530-476f-a710-04964e8abe8c.png) 어떻게 해결해야 하나요?

 안녕하세요
make_up_universe.py에 있는 execute_crawler 함수 아래코드에서 에러가 나신 것 같습니다. 
total_page_num = int(total_page_num.get('href').split('=')[-1]) 

위 코드 윗줄 혹은 make_up_universe.py의 전체 소스를 독자님 깃허브에 올려주시면 확인해보겠습니다.

**Comment by adfhief** [comment]
![image](https://user-images.githubusercontent.com/95861458/153524766-ea30f0c6-4de3-4219-9c6b-549d8f2de959.png)

![image](https://user-images.githubusercontent.com/95861458/153524783-93a5c557-0f90-42a4-a5c4-e86458c651f5.png)


make_up_universe.py 전체 소스입니다.

**Comment by papadaks** [comment]
> 

total_page_num = page_soup.select_one('te.pgRR > a') 라고 작성하셨는데
total_page_num = page_soup.select_one('td.pgRR > a')로 바꿔주세요~

**Comment by adfhief** [comment]
![image](https://user-images.githubusercontent.com/95861458/154411149-398193ce-85ef-4422-987f-eb4f162af71b.png)


코드 수정 후 main.py를 실행했는데 다음과 같은 오류가 발생하였습니다.
RSIStrategy 데이터베이스에 universe 테이블이 없어서 발생하는 오류인가요?

**Comment by papadaks** [comment]
> ![image](https://user-images.githubusercontent.com/95861458/154411149-398193ce-85ef-4422-987f-eb4f162af71b.png)
> 
> 코드 수정 후 main.py를 실행했는데 다음과 같은 오류가 발생하였습니다. RSIStrategy 데이터베이스에 universe 테이블이 없어서 발생하는 오류인가요?

안녕하세요
네 맞습니다
장이 끝난 다음에 프로그램 실행해서 universe 테이블 생성이 되도록 해보시겠어요??

**Comment by adfhief** [comment]
데이터베이스에 universe 테이블이 있는데도 계속 같은 오류가 발생합니다.

**Comment by papadaks** [comment]
> 데이터베이스에 universe 테이블이 있는데도 계속 같은 오류가 발생합니다.

독자님 허브에 캡쳐해주신 소스 전체 올려주시겠어요?
뭔가 잘못되어 있는 것 같습니다
