### ISSUE TITLE
키움Api 로그인하고 주식일봉차트정보 요청시

### ISSUE THREAD

**Issue by bluecupit** [papadaks/SystemTrading#6]
키움 데이터 조건인 5초당 5회는 문제없는데
1000건이 넘어가면 키움에서 접속 차단시킵니다.
그래서 분봉차트정보가 98개까지만 받아지고 더이상 진행이 안되네요.
코드 설명에는 다음 실행시 98번에서 끊겼으면 99번 부터 시작한다고 되어있는데
1번 종목부터 다시 받기 시작합니다. 그래서 다시98번에서 또 접속 차단 당하네요.
rsistrategy.py에는 마지막 받은 분봉데이터 날짜와 현재 날짜를 비교해서 같지 않으면 분봉차트 조회를 실행하는데요..
이게 현재날짜가 공휴일 같은 경유엔 업데이트된 분통차트데이터가 없어도 kioom.py에서 다시 조회요청을 하는데
조회요청을 할 때 최근 600개만 하는게 아니고, 종목 데이터 전부를 요청하더라구요.. 최근 600개만 해서 업데이트 해도, 키움에서 1000개 제한에는 안 걸릴듯한데..
그래서 kioom.py에서 마지막 받은 분봉차트데이터 날짜하고 현재 날짜에서 2년은 뺀 날짜(한번 받을 때 600봉 받아 오니깐 대략 2년이라 보고)비교해서 2년이하면 tr요청을 한번만하고 2년 이상이면 다 실행하도록 해봤는데 자꾸 오류가 나네요
해결 방법 없을까요?

**Comment by papadaks** [comment]
> 

안녕하세요 선생님
프로그램을 수정하시는 것 같습니다
제공드린 프로그램은 일봉데이터를 수집해서 현재 저장된 데이터 일자와 비교 후 해당 종목이 가격 데이터를 받아와야 할지를 
판단하는데요 이미 수집된 종목을 다시 수집한다는 말씀으로 보아 비교조건이 잘못되어 있는 것 같습니다.

깃허브에 수정하신 프로그램을 올려주시고 링크 남겨주시면 문제를 해결하는데 도와드릴 수 있도록 하겠습니다.

**Comment by bluecupit** [comment]
프로그램 수정안했습니다..책 마지막에 나온 깃허브에서 다운받는 방법으로 다운 받고서 실행한 결과입니다.코드보니
rsistrategy.py에서 최근받아온 날짜를 가져와서 현재날짜와 같지않을경우 kiwoom.py에서 tr데이터를 받도록
되어있더라구요..( 날짜가 같지 않을때 tr데이터를 처음부터 다시 받습니다) 코딩 다시한번 확인 부탁드려요..
 비교연산을 rsistrategy.py에서도 해야하지만..kiwoom.py에서도 비교를해서 데이터를 전체 다
가져올지..한번만(600개)가져올지 판단해야할것 같습니다

2022년 2월 3일 (목) 오후 5:36, papadaks ***@***.***>님이 작성:

**Comment by papadaks** [comment]
저장 데이터는 일봉인데 분봉이라고 표현하셔서 직접 수정하신 줄 알았네요..

말씀하신 것처럼 프로그램 상에 허점이 존재하기는 합니다. 
아시겠지만 현재 코드가 오늘 날짜와 데이터베이스에 저장된 가장 최근 날짜를 비교하는 것을 끝으로
다시 TR을 호출할지 판단하기 때문입니다.

now = datetime.now().strftime("%Y%m%d")

if last_date[0] != now:
-----------------------------------------------
이렇게 되면 예를 들어 프로그램  실행일자가 휴일(2022.02.02)이고 최근 저장일자가 2022.01.28라면
더이상 받아올 일봉 데이터가 없음에도 두 비교일자가 다르다는 이유로 TR를 계속 호출하게 합니다만
프로그램이 더 복잡해지는 것을 피하기 위해 오늘이 휴일인지까지 판단하는 로직까지는 추가하지 않았습니다.

만약 위와 같은 휴일 케이스 문제가 아니라면
코드상 last_date[0]로 출력되는 값이 무엇인지, 데이터베이스에 제대로 저장된 것이 맞는지 확인 부탁드립니다.

**Comment by HyeonDuckSeo** [comment]
안녕하세요.
윗 분과 같은 문제로 고통 받고 있습니다.

"""
키움 데이터 조건인 5초당 5회는 문제없는데
1000건이 넘어가면 키움에서 접속 차단시킵니다.
그래서 일봉차트정보가 98개까지만 받아지고 더이상 진행이 안되네요.
코드 설명에는 다음 실행시 98번에서 끊겼으면 99번 부터 시작한다고 되어있는데
1번 종목부터 다시 받기 시작합니다. 그래서 다시98번에서 또 접속 차단 당하네요.
"""

책에서 설명해주신 1번 케이스(일봉 데이터가 없는 경우, 장 종료 이후)로,
RSIStrategy.db에 데이터를 넣는 과정에서 약 (90/200)번째에서 

"현재 고객님 프로그램에서 과도한 조회요청이 발생되고 있습니다.
일시적으로 조회가 차단되었으니, 프로그램을 종료후 재실행 바랍니다.
*반복되는 조회 요청 시간간격에 여유를 두시거나 가능한 실시간 이벤트 및 
실시간 데이터를 사용해주시길 바랍니다."

의 오류창이 나타납니다. 

무엇이 문제인지, 문제의 원인이 무엇인지, 어떻게 해결할 수 있는지 도움을 부탁드립니다.

**Comment by HyeonDuckSeo** [comment]
안녕하세요.
혹시 해결하셨나요?

**Comment by papadaks** [comment]
> 안녕하세요. 윗 분과 같은 문제로 고통 받고 있습니다.
> 
> """ 키움 데이터 조건인 5초당 5회는 문제없는데 1000건이 넘어가면 키움에서 접속 차단시킵니다. 그래서 일봉차트정보가 98개까지만 받아지고 더이상 진행이 안되네요. 코드 설명에는 다음 실행시 98번에서 끊겼으면 99번 부터 시작한다고 되어있는데 1번 종목부터 다시 받기 시작합니다. 그래서 다시98번에서 또 접속 차단 당하네요. """
> 
> 책에서 설명해주신 1번 케이스(일봉 데이터가 없는 경우, 장 종료 이후)로, RSIStrategy.db에 데이터를 넣는 과정에서 약 (90/200)번째에서
> 
> "현재 고객님 프로그램에서 과도한 조회요청이 발생되고 있습니다. 일시적으로 조회가 차단되었으니, 프로그램을 종료후 재실행 바랍니다. *반복되는 조회 요청 시간간격에 여유를 두시거나 가능한 실시간 이벤트 및 실시간 데이터를 사용해주시길 바랍니다."
> 
> 의 오류창이 나타납니다.
> 
> 무엇이 문제인지, 문제의 원인이 무엇인지, 어떻게 해결할 수 있는지 도움을 부탁드립니다.

안녕하세요
독자님 pc에서 동작시킨 프로그램 소스를
깃허브에 올려보시겠어요??

**Comment by HyeonDuckSeo** [comment]
안녕하세요. 

프로그램 소스는 작가님이 작성하신 소스코드와 동일합니다.
제가 궁금한 것은 키움증권 오픈API 조회 제한에 대한 부분입니다.

(1) _on_receive_tr_data 함수의 time.sleep(0.5) 적용해도 오류 없이 구동이 가능한가요?
0.5초 슬립 시 약 90번째에서 항상 오류창이 나타납니다.

(2) 책에서는 "이런 문제가 생기면 프로그램을 재 실행할 때 이미 일봉 데이터를 저장한 종목은 생략하고 넘어가도록 코드를 만들어야 합니다. 그렇지 않으면 모든 종목의 데이터를 저장하지 못하고 계속해서 중간에 멈추는 문제가 생길 수 있습니다." 라고 설명합니다. 실제로 프로그램을 돌려봤을 때, 생략하지 않고 처음부터 다시 데이터를 저장하는데, 해당 설명에 대한 코드가 적용되어 있는 지와 그렇다면 해당 코드를 어디서 찾을 수 있을까요?

(3) 이러한 조회 요청 오류를 피하기 위해 time.sleep(3.6)로 설정한다면 오류를 피할 수 있다는 글을 봤습니다.  _on_receive_tr_data 함수의 time.sleep(3.6) 적용해도 side effect 없이 구동이 가능한가요?
