### ISSUE TITLE
next가 계속 2인 것 같은데 해결 방법은 무엇인가요?

### ISSUE THREAD

**Issue by canbuildit** [papadaks/SystemTrading#8]
안녕하세요, 박준성 님.

책 구매 후 한 장 한 장 따라서 해 보고 있습니다.
P226 내용을 수행하면
[Kiwoom] _on_receive_tr_data is called 0001 / opt10081_req / opt10081라는 문구가 무한 출력됩니다.

next가 2인 Case에서 self.has_next_tr_data를 False로 설정하면
딱 한 번 위의 문구가 뜨고 정보 600줄이 출력됩니다.

특정 시간에 Test 시, next가 계속 2인 경우가 있는 건가요?

**Comment by papadaks** [comment]
> 
특정 시간에 Test 시, next가 계속 2인 경우가 있는 건가요? > 이런 경우는 없습니다. 

또한 데이터를 가져오는 TR인 opt10081은 유한한 데이터를 가져오는 과정이므로
무한히 실행될 수 없습니다. 
그런데도 [Kiwoom] _on_receive_tr_data is called 0001 / opt10081_req / opt10081라는 문구가 무한히 나오는 것은 
어딘가 타이핑이 잘못됐거나 따라하시는 과정에서 빠진 부분이 있는 것 같습니다.
