### ISSUE TITLE
RSIStrategy.py 파일의 132번 라인에서 오류가 발생됩니다.

### ISSUE THREAD

**Issue by sigco3111** [papadaks/SystemTrading#9]
RSIStrategy.py 파일의 132번 라인에서 오류가 발생됩니다.
sql = "select * from `{}`".format(code)

아래와 같이 수정하면 될까요?
sql = "select * from universe WHERE code = '{}'".format(code)

**Comment by papadaks** [comment]
> RSIStrategy.py 파일의 132번 라인에서 오류가 발생됩니다. sql = "select * from `{}`".format(code)
> 
> 아래와 같이 수정하면 될까요? sql = "select * from universe WHERE code = '{}'".format(code)

그렇게 되면 두 쿼리의 의도가 아예 다른 것이 됩니다.
sql = "select * from {}".format(code) 가 에러가 나면
sql = "select * from `{}`".format(code) 이렇게 사용해보시겠어요?

**Comment by sigco3111** [comment]
답변 감사합니다. 덕분에 해결되었습니다.

**Comment by sigco3111** [comment]
답변 감사합니다.

장시작 전에 최초 실행 했을 경우 유니버스를 생성하기 전에 

RSIStrategy.py 파일의 132번 라인 호출되어 오류가 발생되었습니다.

장중에 앱을 실행 시키거나 유니버스 생성 여부를 확인한 후 132번 라인이 호출되게 하면

정상 동작합니다.
